const express = require("express");
const walletController = require("../controllers/wallet.controller");
const router = express.Router();
const { checkToken } = require("../services/authentication");
router.get("/", walletController.create);
router.get("/balance/:id", walletController.getBalance);
router.post("/login", walletController.login);
router.post("/send", walletController.sendTrans);
router.put("/sign/:id", walletController.signTrans);
router.get("/getTrans/:address", walletController.getTrans);
module.exports = router;
